/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILETRANSFER_H_RPCGEN
#define _FILETRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXFILEDATA 4096

struct FileChunk {
	char *filename;
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int size;
};
typedef struct FileChunk FileChunk;

#define FILETRANSFER_PROG 0x31234567
#define FILETRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define send_chunk 1
extern  int * send_chunk_1(FileChunk *, CLIENT *);
extern  int * send_chunk_1_svc(FileChunk *, struct svc_req *);
extern int filetransfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define send_chunk 1
extern  int * send_chunk_1();
extern  int * send_chunk_1_svc();
extern int filetransfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileChunk (XDR *, FileChunk*);

#else /* K&R C */
extern bool_t xdr_FileChunk ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILETRANSFER_H_RPCGEN */
