/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filetransfer.h"

bool_t
xdr_FileChunk (XDR *xdrs, FileChunk *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, 256))
		 return FALSE;
	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, MAXFILEDATA))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
